struct Person {string firstname; string lastname; int age;};

struct ThreePeople {
  Person p1;
  Person p2;
  Person p3;
};

string getfirstname(Person p);
Person findPerson(ThreePeople tp);

struct StructWithArrays {
  int aNumber;
  Person people[10];
};

struct rectangle {int x; int y;};

int area(rectangle r);

